# Generated by Django 6.0.7 on 2026-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='invoice_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='shop_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
