# Generated by Django 6.0.7 on 2026-07-20 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salesbill',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='original_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bills', to='core.salesbill'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_bills', to='core.employee'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ChequePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=50)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_detail', to='core.salesbill')),
            ],
        ),
        migrations.CreateModel(
            name='MultiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_1', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('amount_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type_2', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('amount_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_detail', to='core.salesbill')),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Mobile Wallet', 'Mobile Wallet'), ('Card', 'Card'), ('Other', 'Other')], max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_detail', to='core.salesbill')),
            ],
        ),
    ]
