# Generated by Django 6.0.7 on 2026-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supplier_purchase_purchaseitem_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('CREDIT', 'Credit Purchases'), ('COMPLETE', 'Complete Payment')], default='PENDING', max_length=20),
        ),
    ]
