# Generated by Django 6.0.7 on 2026-07-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings')], default='CURRENT', max_length=20),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=50)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(help_text='Customer who gave the cheque', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPOSITED', 'Deposited'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('bounce_reason', models.CharField(blank=True, help_text='Reason if bounced', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='core.bank')),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='core.salesbill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
