# Generated by Django 6.0.7 on 2026-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bank_account_no_bank_account_type_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer/Shop name', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=50, unique=True)),
                ('customer_type', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('CORPORATE', 'Corporate'), ('OTHER', 'Other')], default='RETAIL', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, help_text='VAT/TIN number', max_length=50, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed (0 = unlimited)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
