# Generated by Django 6.0.7 on 2026-07-23 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cheque', 'Cheque'), ('Online', 'Online')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Maintenance', 'Maintenance / Repairs'), ('Tires', 'Tires'), ('Spare Parts', 'Spare Parts'), ('Vehicle Insurance', 'Vehicle Insurance'), ('Vehicle Registration', 'Vehicle Registration'), ('Toll Charges', 'Toll Charges'), ('Parking Fees', 'Parking Fees'), ('Washing', 'Washing / Cleaning'), ('Driver Allowance', 'Driver Allowance'), ('Salaries', 'Salaries'), ('Bonuses', 'Bonuses'), ('Overtime', 'Overtime'), ('Medical', 'Medical / Health'), ('Uniforms', 'Uniforms'), ('Training', 'Training'), ('Meals', 'Staff Meals'), ('Warehouse Rent', 'Warehouse Rent'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Phone Bills', 'Phone Bills'), ('Office Supplies', 'Office Supplies'), ('Cleaning', 'Cleaning'), ('Security', 'Security'), ('Business Insurance', 'Business Insurance'), ('Rates & Taxes', 'Rates & Taxes'), ('Advertising', 'Advertising'), ('Promotions', 'Promotions'), ('Sampling', 'Sampling'), ('Sales Materials', 'Sales Materials'), ('Customer Events', 'Customer Events'), ('Bank Charges', 'Bank Charges'), ('Legal Fees', 'Legal Fees'), ('Accounting', 'Accounting'), ('Consulting', 'Consulting'), ('Licenses', 'Licenses'), ('Subscriptions', 'Subscriptions'), ('Memberships', 'Memberships'), ('Donations', 'Donations'), ('Gifts', 'Gifts'), ('Travel', 'Travel'), ('Postage', 'Postage'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.vehicle'),
        ),
    ]
