# Generated by Django 6.0.7 on 2026-07-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vehicle_options_vehicle_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('BREAKDOWN', 'Vehicle Breakdown'), ('ROUTE_CHANGE', 'Route Change'), ('STOCK_BALANCE', 'Stock Balancing'), ('DRIVER_CHANGE', 'Driver Change'), ('OTHER', 'Other')], default='STOCK_BALANCE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.vehicle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('source_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.vehicle')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
    ]
