# Generated by Django 6.0.7 on 2026-07-24 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stocktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken for Collection'), ('COLLECTED', 'Collected'), ('NOT_COLLECTED', 'Not Collected')], default='PENDING', max_length=20)),
                ('collection_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20, null=True)),
                ('not_collected_reason', models.CharField(blank=True, choices=[('CUSTOMER_NOT_AVAILABLE', 'Customer Not Available'), ('REFUSED_TO_PAY', 'Customer Refused to Pay'), ('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('CUSTOMER_REQUESTED_DELAY', 'Customer Requested Delay'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_done', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.employee')),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.salesbill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
