# Generated by Django 6.0.7 on 2026-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_creditcollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='rep_code',
            field=models.CharField(blank=True, help_text='Unique code for Sales Representatives (e.g., 008SIN)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rep_invoice_counter',
            field=models.IntegerField(default=0, help_text='Last invoice number used for this Rep'),
        ),
    ]
