# Generated by Django 6.0.7 on 2026-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_employee_options_employee_rep_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='invoice_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
