# Generated by Django 6.0.7 on 2026-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_salesbill_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='is_foc',
            field=models.BooleanField(default=False),
        ),
    ]
