# Generated by Django 6.0.7 on 2026-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_salesitem_is_foc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='is_foc',
            field=models.BooleanField(default=False),
        ),
    ]
