# Generated by Django 6.0.7 on 2026-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cheque_bank_charge_amount_cheque_bank_charge_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='bill_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='bill_discount_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='bill_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discounted_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
