# Generated by Django 6.0.7 on 2026-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_salesbill_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
