# Generated by Django 6.0.7 on 2026-08-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_vehicleload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleload',
            name='loaded_by',
        ),
    ]
