# Generated by Django 6.0.7 on 2026-08-28 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
