# Generated by Django 6.0.7 on 2026-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_cheque_bank_charge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
