# Generated by Django 6.0.7 on 2026-08-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_salesbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reversed_cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cheque'),
        ),
    ]
