# Generated by Django 6.0.7 on 2026-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_payment_reversed_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='foc_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
