# Generated by Django 6.0.7 on 2026-09-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={},
        ),
    ]
