# Generated by Django 6.0.7 on 2026-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_productprice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbill',
            name='original_bill',
        ),
        migrations.AddField(
            model_name='salesbill',
            name='return_type',
            field=models.CharField(choices=[('NONE', 'No Return'), ('GOOD', 'Good Return'), ('BAD', 'Bad Return')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='return_type',
            field=models.CharField(choices=[('NONE', 'No Return'), ('GOOD', 'Good Return'), ('BAD', 'Bad Return')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='return_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='return_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
