# Generated by Django 6.0.7 on 2026-09-06 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_salesbill_original_bill_salesbill_return_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vehicleload',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
