# Generated by Django 6.0.7 on 2026-09-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_stockmovementlog_date_stocktransfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rep_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
