# Generated by Django 6.0.7 on 2026-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Mark if this is a VAT bill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
