# Generated by Django 6.0.7 on 2026-09-30 16:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_purchase_is_vat_bill_userprofile_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(help_text='Auto-generated return number', max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('shop_name', models.CharField(blank=True, max_length=200)),
                ('shop_code', models.CharField(blank=True, max_length=50)),
                ('return_type', models.CharField(choices=[('GOOD', '✅ Good Return'), ('BAD', '❌ Bad Return')], default='GOOD', max_length=10)),
                ('return_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('return_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of returned items', max_digits=15)),
                ('exchange_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of new items given in exchange', max_digits=15)),
                ('net_credit', models.DecimalField(decimal_places=2, default=0, help_text='Return Value - Exchange Value', max_digits=15)),
                ('settlement_type', models.CharField(choices=[('CREDIT', 'Customer Credit Outstanding'), ('DAY_BILL', "Deduct from Today's Bill"), ('CASH', 'Cash Refund'), ('NONE', 'No Settlement (Full Exchange)')], default='CREDIT', max_length=20)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount applied to credit/bill', max_digits=15)),
                ('cash_refunded', models.DecimalField(decimal_places=2, default=0, help_text='Cash given to customer', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.customer')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.salesbill')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_items', to='core.salesreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='core.salesreturn')),
            ],
        ),
    ]
