# Generated by Django 6.0.7 on 2026-09-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_salesreturn_salesreturnexchangeitem_salesreturnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.IntegerField(default=30, help_text='Max days after sale to accept a return')),
                ('require_return_approval_above', models.DecimalField(decimal_places=2, default=50000, help_text='Returns above this amount require approval', max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
