# Generated by Django 6.0.7 on 2026-10-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Mark if this is a VAT bill'),
        ),
    ]
